import '../scss/style.scss'
import '../scss/blocks/read-more/read-more.js'
import '../scss/blocks/menu-mobile/menu-mobile.js'
import '../scss/blocks/toggle/toggle.js'
import '../scss/blocks/brands/brands.js'
import '../scss/blocks/types/types.js'